export enum NotificationChannel {
  EMAIL = 'EMAIL',
  PUSH = 'PUSH',
  SMS = 'SMS',
  IN_APP = 'IN_APP',
  WEBHOOK = 'WEBHOOK',
}

export enum NotificationTriggerEvent {
  // Identity Service
  USER_REGISTERED_WELCOME = 'USER_REGISTERED_WELCOME',
  USER_REGISTRATION_OTP = 'USER_REGISTRATION_OTP',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',

  SELLER_PROFILE_APPROVED = 'SELLER_PROFILE_APPROVED',

  // Orders & Checkout Service
  ORDER_CREATED_CONFIRMATION = 'ORDER_CREATED_CONFIRMATION',
  ORDER_PAID_SUCCESS = 'ORDER_PAID_SUCCESS',
  ORDER_SHIPPED_UPDATE = 'ORDER_SHIPPED_UPDATE',

  // Invoicing Service
  INVOICE_CREATED = 'INVOICE_CREATED',

  // Events & RSVP Service
  EVENT_REMINDER_24H = 'EVENT_REMINDER_24H',
  RSVP_CONFIRMED = 'RSVP_CONFIRMED',

  // Messaging Service
  NEW_MESSAGE_RECEIVED = 'NEW_MESSAGE_RECEIVED',

  // Marketing & CRM Service
  MARKETING_CAMPAIGN_EMAIL = 'MARKETING_CAMPAIGN_EMAIL',

  // Another general cases
  GENERIC_ALERT = 'GENERIC_ALERT',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
  FAILED = 'FAILED',
}
