/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArtAuctionEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auctions"
      | "bid"
      | "confirmDelivery"
      | "createAuction"
      | "endAuction"
      | "pendingReturns"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionEnded"
      | "AuctionStarted"
      | "DeliveryConfirmed"
      | "NewBid"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "auctions", values: [string]): string;
  encodeFunctionData(functionFragment: "bid", values: [string]): string;
  encodeFunctionData(
    functionFragment: "confirmDelivery",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "endAuction", values: [string]): string;
  encodeFunctionData(
    functionFragment: "pendingReturns",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endAuction", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingReturns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AuctionEndedEvent {
  export type InputTuple = [
    orderId: string,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [orderId: string, winner: string, amount: bigint];
  export interface OutputObject {
    orderId: string;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionStartedEvent {
  export type InputTuple = [
    orderId: string,
    seller: AddressLike,
    endTime: BigNumberish
  ];
  export type OutputTuple = [orderId: string, seller: string, endTime: bigint];
  export interface OutputObject {
    orderId: string;
    seller: string;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliveryConfirmedEvent {
  export type InputTuple = [orderId: string, winner: AddressLike];
  export type OutputTuple = [orderId: string, winner: string];
  export interface OutputObject {
    orderId: string;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewBidEvent {
  export type InputTuple = [
    orderId: string,
    bidder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [orderId: string, bidder: string, amount: bigint];
  export interface OutputObject {
    orderId: string;
    bidder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [bidder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [bidder: string, amount: bigint];
  export interface OutputObject {
    bidder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArtAuctionEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ArtAuctionEscrow;
  waitForDeployment(): Promise<this>;

  interface: ArtAuctionEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auctions: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, bigint] & {
        seller: string;
        highestBidder: string;
        highestBid: bigint;
        endTime: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  bid: TypedContractMethod<[orderId: string], [void], "payable">;

  confirmDelivery: TypedContractMethod<[orderId: string], [void], "nonpayable">;

  createAuction: TypedContractMethod<
    [orderId: string, seller: AddressLike, duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  endAuction: TypedContractMethod<[orderId: string], [void], "nonpayable">;

  pendingReturns: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auctions"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, bigint] & {
        seller: string;
        highestBidder: string;
        highestBid: bigint;
        endTime: bigint;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bid"
  ): TypedContractMethod<[orderId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "confirmDelivery"
  ): TypedContractMethod<[orderId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createAuction"
  ): TypedContractMethod<
    [orderId: string, seller: AddressLike, duration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "endAuction"
  ): TypedContractMethod<[orderId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pendingReturns"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AuctionEnded"
  ): TypedContractEvent<
    AuctionEndedEvent.InputTuple,
    AuctionEndedEvent.OutputTuple,
    AuctionEndedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionStarted"
  ): TypedContractEvent<
    AuctionStartedEvent.InputTuple,
    AuctionStartedEvent.OutputTuple,
    AuctionStartedEvent.OutputObject
  >;
  getEvent(
    key: "DeliveryConfirmed"
  ): TypedContractEvent<
    DeliveryConfirmedEvent.InputTuple,
    DeliveryConfirmedEvent.OutputTuple,
    DeliveryConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "NewBid"
  ): TypedContractEvent<
    NewBidEvent.InputTuple,
    NewBidEvent.OutputTuple,
    NewBidEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "AuctionEnded(string,address,uint256)": TypedContractEvent<
      AuctionEndedEvent.InputTuple,
      AuctionEndedEvent.OutputTuple,
      AuctionEndedEvent.OutputObject
    >;
    AuctionEnded: TypedContractEvent<
      AuctionEndedEvent.InputTuple,
      AuctionEndedEvent.OutputTuple,
      AuctionEndedEvent.OutputObject
    >;

    "AuctionStarted(string,address,uint256)": TypedContractEvent<
      AuctionStartedEvent.InputTuple,
      AuctionStartedEvent.OutputTuple,
      AuctionStartedEvent.OutputObject
    >;
    AuctionStarted: TypedContractEvent<
      AuctionStartedEvent.InputTuple,
      AuctionStartedEvent.OutputTuple,
      AuctionStartedEvent.OutputObject
    >;

    "DeliveryConfirmed(string,address)": TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;
    DeliveryConfirmed: TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;

    "NewBid(string,address,uint256)": TypedContractEvent<
      NewBidEvent.InputTuple,
      NewBidEvent.OutputTuple,
      NewBidEvent.OutputObject
    >;
    NewBid: TypedContractEvent<
      NewBidEvent.InputTuple,
      NewBidEvent.OutputTuple,
      NewBidEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
