apiVersion: v1
kind: Service
metadata:
  name: artworks-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: artworks-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
      nodePort: 32003