apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: dev
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog:latest
          ports:
            - containerPort: 1025
            - containerPort: 8025
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"

apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: dev
spec:
  type: NodePort
  selector:
    app: mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
      nodePort: 31025
    - name: web
      port: 8025
      targetPort: 8025
      nodePort: 32025
