apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: dev
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "myuser"
            - name: RABBITMQ_DEFAULT_PASS
              value: "mypassword"
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          resources:
            limits:
              cpu: "500m"
              memory: "768Mi"
            requests:
              cpu: "400m"
              memory: "384Mi"

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: dev
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30572
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 31672
