/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IArtAuctionEscrowExternal,
  IArtAuctionEscrowExternalInterface,
} from "../../../../contracts/test/AdversarialHelpers.sol/IArtAuctionEscrowExternal";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "orderId",
        type: "string",
      },
    ],
    name: "bid",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "orderId",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "reservePrice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minBidIncrement",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "ipfsHash",
        type: "string",
      },
    ],
    name: "createAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "orderId",
        type: "string",
      },
    ],
    name: "endAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "orderId",
        type: "string",
      },
      {
        internalType: "string",
        name: "trackingHash",
        type: "string",
      },
    ],
    name: "markShipped",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IArtAuctionEscrowExternal__factory {
  static readonly abi = _abi;
  static createInterface(): IArtAuctionEscrowExternalInterface {
    return new Interface(_abi) as IArtAuctionEscrowExternalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IArtAuctionEscrowExternal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IArtAuctionEscrowExternal;
  }
}
