/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  RejectEtherReceiver,
  RejectEtherReceiverInterface,
} from "../../../../contracts/test/AdversarialHelpers.sol/RejectEtherReceiver";

const _abi = [
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50607d8061001e6000396000f3fe60806040523660425760405162461bcd60e51b815260206004820152600b60248201526a2932b532b1ba22ba3432b960a91b604482015260640160405180910390fd5b600080fdfea2646970667358221220f4510b8013a5f04bc571f9dc82dc47edfdad05fefabadf383a1df4b4b138f62a64736f6c63430008140033";

type RejectEtherReceiverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RejectEtherReceiverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RejectEtherReceiver__factory extends ContractFactory {
  constructor(...args: RejectEtherReceiverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      RejectEtherReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): RejectEtherReceiver__factory {
    return super.connect(runner) as RejectEtherReceiver__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RejectEtherReceiverInterface {
    return new Interface(_abi) as RejectEtherReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RejectEtherReceiver {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as RejectEtherReceiver;
  }
}
