/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  RevertingBidder,
  RevertingBidderInterface,
} from "../../../../contracts/test/AdversarialHelpers.sol/RevertingBidder";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "escrowAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "escrow",
    outputs: [
      {
        internalType: "contract IArtAuctionEscrowExternal",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "orderId",
        type: "string",
      },
    ],
    name: "placeBid",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawFromEscrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161035f38038061035f83398101604081905261002f91610040565b6001600160a01b0316608052610070565b60006020828403121561005257600080fd5b81516001600160a01b038116811461006957600080fd5b9392505050565b6080516102c86100976000396000818160a50152818160f8015261018201526102c86000f3fe6080604052600436106100385760003560e01c8063b725d6721461007c578063e2fdcc1714610093578063e967e60c146100e357600080fd5b366100775760405162461bcd60e51b815260206004820152600b60248201526a2932b532b1ba22ba3432b960a91b604482015260640160405180910390fd5b600080fd5b34801561008857600080fd5b506100916100f6565b005b34801561009f57600080fd5b506100c77f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b03909116815260200160405180910390f35b6100916100f13660046101f1565b61016b565b7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316633ccfd60b6040518163ffffffff1660e01b8152600401600060405180830381600087803b15801561015157600080fd5b505af1158015610165573d6000803e3d6000fd5b50505050565b604051631ebbe54760e21b81526001600160a01b037f00000000000000000000000000000000000000000000000000000000000000001690637aef951c9034906101bb9086908690600401610263565b6000604051808303818588803b1580156101d457600080fd5b505af11580156101e8573d6000803e3d6000fd5b50505050505050565b6000806020838503121561020457600080fd5b823567ffffffffffffffff8082111561021c57600080fd5b818501915085601f83011261023057600080fd5b81358181111561023f57600080fd5b86602082850101111561025157600080fd5b60209290920196919550909350505050565b60208152816020820152818360408301376000818301604090810191909152601f909201601f1916010191905056fea2646970667358221220ecc61ddd1b5175a6bab6ce6b8d7172208256a467cdab382afce12ab96ef75c8164736f6c63430008140033";

type RevertingBidderConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RevertingBidderConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RevertingBidder__factory extends ContractFactory {
  constructor(...args: RevertingBidderConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    escrowAddress: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(escrowAddress, overrides || {});
  }
  override deploy(
    escrowAddress: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(escrowAddress, overrides || {}) as Promise<
      RevertingBidder & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): RevertingBidder__factory {
    return super.connect(runner) as RevertingBidder__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RevertingBidderInterface {
    return new Interface(_abi) as RevertingBidderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RevertingBidder {
    return new Contract(address, _abi, runner) as unknown as RevertingBidder;
  }
}
