/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "ArtAuctionEscrow",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ArtAuctionEscrow__factory>;
    getContractFactory(
      name: "IArtAuctionEscrowExternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IArtAuctionEscrowExternal__factory>;
    getContractFactory(
      name: "RejectEtherReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RejectEtherReceiver__factory>;
    getContractFactory(
      name: "RevertingBidder",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RevertingBidder__factory>;
    getContractFactory(
      name: "RevertingSellerAgent",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RevertingSellerAgent__factory>;

    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "ArtAuctionEscrow",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ArtAuctionEscrow>;
    getContractAt(
      name: "IArtAuctionEscrowExternal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IArtAuctionEscrowExternal>;
    getContractAt(
      name: "RejectEtherReceiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RejectEtherReceiver>;
    getContractAt(
      name: "RevertingBidder",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RevertingBidder>;
    getContractAt(
      name: "RevertingSellerAgent",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RevertingSellerAgent>;

    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "ArtAuctionEscrow",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArtAuctionEscrow>;
    deployContract(
      name: "IArtAuctionEscrowExternal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IArtAuctionEscrowExternal>;
    deployContract(
      name: "RejectEtherReceiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RejectEtherReceiver>;
    deployContract(
      name: "RevertingBidder",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RevertingBidder>;
    deployContract(
      name: "RevertingSellerAgent",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RevertingSellerAgent>;

    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "ArtAuctionEscrow",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArtAuctionEscrow>;
    deployContract(
      name: "IArtAuctionEscrowExternal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IArtAuctionEscrowExternal>;
    deployContract(
      name: "RejectEtherReceiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RejectEtherReceiver>;
    deployContract(
      name: "RevertingBidder",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RevertingBidder>;
    deployContract(
      name: "RevertingSellerAgent",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RevertingSellerAgent>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
