/**
 * UPLOAD_TAG_OPTIONS - React component
 * @returns React element
 */
export const UPLOAD_TAG_OPTIONS = {
  vibes: [
    'Joyful',
    'Natural',
    'Vibrant',
    'Expressive',
    'Peaceful',
    'Romantic',
    'Bold',
    'Dreamy',
    'Classic',
    'Moody',
    'Minimalist',
    'Vintage',
    'Avant Garde',
    'Spiritual',
    'Melancholic',
    'Other',
  ],
  values: [
    'Cultural Heritage',
    'Human Experience',
    'Pride',
    'Futurism',
    'Environment',
    'Equity',
    'Feminism',
    'Social Awareness',
    'Escapism',
    'Empowerment',
    'Universal',
    'Other',
  ],
  mediums: [
    'Painting',
    'Drawing',
    'Illustration',
    'Digital Art',
    'Photography',
    'Sculpture',
    'Installation',
    'Collage',
    'Immersive',
    'Mixed Media',
    'Performance Art',
    'Prints',
    'Public Art',
    'Video',
    'Ceramics',
    'Animation',
    'Jewelry',
    'Textile',
    'Designed Objects',
    'Functional Art',
    'Concept Art',
    'Intellectual Art',
    'Other',
  ],
}
