/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArtAuctionEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ANTI_SNIPE_EXTENSION"
      | "ANTI_SNIPE_WINDOW"
      | "DELIVERY_WINDOW"
      | "DISPUTE_WINDOW"
      | "MAX_FEE_BPS"
      | "SHIPPING_WINDOW"
      | "arbiter"
      | "bid"
      | "cancelAuction"
      | "claimDeliveryTimeout"
      | "claimDisputeTimeout"
      | "claimShippingTimeout"
      | "confirmDelivery"
      | "createAuction"
      | "endAuction"
      | "getAuction"
      | "getAuctionTimeline"
      | "markShipped"
      | "openDispute"
      | "pendingReturns"
      | "platformFeeBps"
      | "platformWallet"
      | "resolveDispute"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArtShipped"
      | "AuctionCancelled"
      | "AuctionEnded"
      | "AuctionExtended"
      | "AuctionStarted"
      | "DeliveryConfirmed"
      | "DeliveryTimeout"
      | "DisputeOpened"
      | "DisputeResolved"
      | "NewBid"
      | "ShippingTimeout"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ANTI_SNIPE_EXTENSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ANTI_SNIPE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DELIVERY_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHIPPING_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "arbiter", values?: undefined): string;
  encodeFunctionData(functionFragment: "bid", values: [string]): string;
  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDeliveryTimeout",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDisputeTimeout",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimShippingTimeout",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmDelivery",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [string, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "endAuction", values: [string]): string;
  encodeFunctionData(functionFragment: "getAuction", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAuctionTimeline",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "markShipped",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingReturns",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [string, boolean]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "ANTI_SNIPE_EXTENSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ANTI_SNIPE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DELIVERY_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SHIPPING_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "arbiter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDeliveryTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDisputeTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimShippingTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endAuction", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAuction", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionTimeline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markShipped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingReturns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ArtShippedEvent {
  export type InputTuple = [
    orderId: string,
    seller: AddressLike,
    trackingHash: string
  ];
  export type OutputTuple = [
    orderId: string,
    seller: string,
    trackingHash: string
  ];
  export interface OutputObject {
    orderId: string;
    seller: string;
    trackingHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionCancelledEvent {
  export type InputTuple = [orderId: string, reason: string];
  export type OutputTuple = [orderId: string, reason: string];
  export interface OutputObject {
    orderId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionEndedEvent {
  export type InputTuple = [
    orderId: string,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [orderId: string, winner: string, amount: bigint];
  export interface OutputObject {
    orderId: string;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionExtendedEvent {
  export type InputTuple = [orderId: string, newEndTime: BigNumberish];
  export type OutputTuple = [orderId: string, newEndTime: bigint];
  export interface OutputObject {
    orderId: string;
    newEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionStartedEvent {
  export type InputTuple = [
    orderId: string,
    seller: AddressLike,
    endTime: BigNumberish
  ];
  export type OutputTuple = [orderId: string, seller: string, endTime: bigint];
  export interface OutputObject {
    orderId: string;
    seller: string;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliveryConfirmedEvent {
  export type InputTuple = [orderId: string, winner: AddressLike];
  export type OutputTuple = [orderId: string, winner: string];
  export interface OutputObject {
    orderId: string;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliveryTimeoutEvent {
  export type InputTuple = [orderId: string, seller: AddressLike];
  export type OutputTuple = [orderId: string, seller: string];
  export interface OutputObject {
    orderId: string;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeOpenedEvent {
  export type InputTuple = [
    orderId: string,
    buyer: AddressLike,
    reason: string
  ];
  export type OutputTuple = [orderId: string, buyer: string, reason: string];
  export interface OutputObject {
    orderId: string;
    buyer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    orderId: string,
    arbiter: AddressLike,
    favorBuyer: boolean
  ];
  export type OutputTuple = [
    orderId: string,
    arbiter: string,
    favorBuyer: boolean
  ];
  export interface OutputObject {
    orderId: string;
    arbiter: string;
    favorBuyer: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewBidEvent {
  export type InputTuple = [
    orderId: string,
    bidder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [orderId: string, bidder: string, amount: bigint];
  export interface OutputObject {
    orderId: string;
    bidder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShippingTimeoutEvent {
  export type InputTuple = [orderId: string, buyer: AddressLike];
  export type OutputTuple = [orderId: string, buyer: string];
  export interface OutputObject {
    orderId: string;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [bidder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [bidder: string, amount: bigint];
  export interface OutputObject {
    bidder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArtAuctionEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ArtAuctionEscrow;
  waitForDeployment(): Promise<this>;

  interface: ArtAuctionEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ANTI_SNIPE_EXTENSION: TypedContractMethod<[], [bigint], "view">;

  ANTI_SNIPE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  DELIVERY_WINDOW: TypedContractMethod<[], [bigint], "view">;

  DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  MAX_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  SHIPPING_WINDOW: TypedContractMethod<[], [bigint], "view">;

  arbiter: TypedContractMethod<[], [string], "view">;

  bid: TypedContractMethod<[orderId: string], [void], "payable">;

  cancelAuction: TypedContractMethod<[orderId: string], [void], "nonpayable">;

  claimDeliveryTimeout: TypedContractMethod<
    [orderId: string],
    [void],
    "nonpayable"
  >;

  claimDisputeTimeout: TypedContractMethod<
    [orderId: string],
    [void],
    "nonpayable"
  >;

  claimShippingTimeout: TypedContractMethod<
    [orderId: string],
    [void],
    "nonpayable"
  >;

  confirmDelivery: TypedContractMethod<[orderId: string], [void], "nonpayable">;

  createAuction: TypedContractMethod<
    [
      orderId: string,
      duration: BigNumberish,
      reservePrice: BigNumberish,
      minBidIncrement: BigNumberish,
      ipfsHash: string
    ],
    [void],
    "nonpayable"
  >;

  endAuction: TypedContractMethod<[orderId: string], [void], "nonpayable">;

  getAuction: TypedContractMethod<
    [orderId: string],
    [
      [string, string, bigint, bigint, bigint, bigint, string, bigint] & {
        seller: string;
        highestBidder: string;
        highestBid: bigint;
        startTime: bigint;
        endTime: bigint;
        minBidIncrement: bigint;
        ipfsHash: string;
        state: bigint;
      }
    ],
    "view"
  >;

  getAuctionTimeline: TypedContractMethod<
    [orderId: string],
    [
      [string, bigint, bigint, bigint, bigint] & {
        trackingHash: string;
        shippingDeadline: bigint;
        deliveryDeadline: bigint;
        disputeDeadline: bigint;
        reservePrice: bigint;
      }
    ],
    "view"
  >;

  markShipped: TypedContractMethod<
    [orderId: string, _trackingHash: string],
    [void],
    "nonpayable"
  >;

  openDispute: TypedContractMethod<
    [orderId: string, reason: string],
    [void],
    "nonpayable"
  >;

  pendingReturns: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  platformWallet: TypedContractMethod<[], [string], "view">;

  resolveDispute: TypedContractMethod<
    [orderId: string, favorBuyer: boolean],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ANTI_SNIPE_EXTENSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ANTI_SNIPE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DELIVERY_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SHIPPING_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "arbiter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bid"
  ): TypedContractMethod<[orderId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "cancelAuction"
  ): TypedContractMethod<[orderId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimDeliveryTimeout"
  ): TypedContractMethod<[orderId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimDisputeTimeout"
  ): TypedContractMethod<[orderId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimShippingTimeout"
  ): TypedContractMethod<[orderId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmDelivery"
  ): TypedContractMethod<[orderId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createAuction"
  ): TypedContractMethod<
    [
      orderId: string,
      duration: BigNumberish,
      reservePrice: BigNumberish,
      minBidIncrement: BigNumberish,
      ipfsHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "endAuction"
  ): TypedContractMethod<[orderId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAuction"
  ): TypedContractMethod<
    [orderId: string],
    [
      [string, string, bigint, bigint, bigint, bigint, string, bigint] & {
        seller: string;
        highestBidder: string;
        highestBid: bigint;
        startTime: bigint;
        endTime: bigint;
        minBidIncrement: bigint;
        ipfsHash: string;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAuctionTimeline"
  ): TypedContractMethod<
    [orderId: string],
    [
      [string, bigint, bigint, bigint, bigint] & {
        trackingHash: string;
        shippingDeadline: bigint;
        deliveryDeadline: bigint;
        disputeDeadline: bigint;
        reservePrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markShipped"
  ): TypedContractMethod<
    [orderId: string, _trackingHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<
    [orderId: string, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pendingReturns"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [orderId: string, favorBuyer: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ArtShipped"
  ): TypedContractEvent<
    ArtShippedEvent.InputTuple,
    ArtShippedEvent.OutputTuple,
    ArtShippedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionCancelled"
  ): TypedContractEvent<
    AuctionCancelledEvent.InputTuple,
    AuctionCancelledEvent.OutputTuple,
    AuctionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "AuctionEnded"
  ): TypedContractEvent<
    AuctionEndedEvent.InputTuple,
    AuctionEndedEvent.OutputTuple,
    AuctionEndedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionExtended"
  ): TypedContractEvent<
    AuctionExtendedEvent.InputTuple,
    AuctionExtendedEvent.OutputTuple,
    AuctionExtendedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionStarted"
  ): TypedContractEvent<
    AuctionStartedEvent.InputTuple,
    AuctionStartedEvent.OutputTuple,
    AuctionStartedEvent.OutputObject
  >;
  getEvent(
    key: "DeliveryConfirmed"
  ): TypedContractEvent<
    DeliveryConfirmedEvent.InputTuple,
    DeliveryConfirmedEvent.OutputTuple,
    DeliveryConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "DeliveryTimeout"
  ): TypedContractEvent<
    DeliveryTimeoutEvent.InputTuple,
    DeliveryTimeoutEvent.OutputTuple,
    DeliveryTimeoutEvent.OutputObject
  >;
  getEvent(
    key: "DisputeOpened"
  ): TypedContractEvent<
    DisputeOpenedEvent.InputTuple,
    DisputeOpenedEvent.OutputTuple,
    DisputeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "NewBid"
  ): TypedContractEvent<
    NewBidEvent.InputTuple,
    NewBidEvent.OutputTuple,
    NewBidEvent.OutputObject
  >;
  getEvent(
    key: "ShippingTimeout"
  ): TypedContractEvent<
    ShippingTimeoutEvent.InputTuple,
    ShippingTimeoutEvent.OutputTuple,
    ShippingTimeoutEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "ArtShipped(string,address,string)": TypedContractEvent<
      ArtShippedEvent.InputTuple,
      ArtShippedEvent.OutputTuple,
      ArtShippedEvent.OutputObject
    >;
    ArtShipped: TypedContractEvent<
      ArtShippedEvent.InputTuple,
      ArtShippedEvent.OutputTuple,
      ArtShippedEvent.OutputObject
    >;

    "AuctionCancelled(string,string)": TypedContractEvent<
      AuctionCancelledEvent.InputTuple,
      AuctionCancelledEvent.OutputTuple,
      AuctionCancelledEvent.OutputObject
    >;
    AuctionCancelled: TypedContractEvent<
      AuctionCancelledEvent.InputTuple,
      AuctionCancelledEvent.OutputTuple,
      AuctionCancelledEvent.OutputObject
    >;

    "AuctionEnded(string,address,uint256)": TypedContractEvent<
      AuctionEndedEvent.InputTuple,
      AuctionEndedEvent.OutputTuple,
      AuctionEndedEvent.OutputObject
    >;
    AuctionEnded: TypedContractEvent<
      AuctionEndedEvent.InputTuple,
      AuctionEndedEvent.OutputTuple,
      AuctionEndedEvent.OutputObject
    >;

    "AuctionExtended(string,uint256)": TypedContractEvent<
      AuctionExtendedEvent.InputTuple,
      AuctionExtendedEvent.OutputTuple,
      AuctionExtendedEvent.OutputObject
    >;
    AuctionExtended: TypedContractEvent<
      AuctionExtendedEvent.InputTuple,
      AuctionExtendedEvent.OutputTuple,
      AuctionExtendedEvent.OutputObject
    >;

    "AuctionStarted(string,address,uint256)": TypedContractEvent<
      AuctionStartedEvent.InputTuple,
      AuctionStartedEvent.OutputTuple,
      AuctionStartedEvent.OutputObject
    >;
    AuctionStarted: TypedContractEvent<
      AuctionStartedEvent.InputTuple,
      AuctionStartedEvent.OutputTuple,
      AuctionStartedEvent.OutputObject
    >;

    "DeliveryConfirmed(string,address)": TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;
    DeliveryConfirmed: TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;

    "DeliveryTimeout(string,address)": TypedContractEvent<
      DeliveryTimeoutEvent.InputTuple,
      DeliveryTimeoutEvent.OutputTuple,
      DeliveryTimeoutEvent.OutputObject
    >;
    DeliveryTimeout: TypedContractEvent<
      DeliveryTimeoutEvent.InputTuple,
      DeliveryTimeoutEvent.OutputTuple,
      DeliveryTimeoutEvent.OutputObject
    >;

    "DisputeOpened(string,address,string)": TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;
    DisputeOpened: TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;

    "DisputeResolved(string,address,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "NewBid(string,address,uint256)": TypedContractEvent<
      NewBidEvent.InputTuple,
      NewBidEvent.OutputTuple,
      NewBidEvent.OutputObject
    >;
    NewBid: TypedContractEvent<
      NewBidEvent.InputTuple,
      NewBidEvent.OutputTuple,
      NewBidEvent.OutputObject
    >;

    "ShippingTimeout(string,address)": TypedContractEvent<
      ShippingTimeoutEvent.InputTuple,
      ShippingTimeoutEvent.OutputTuple,
      ShippingTimeoutEvent.OutputObject
    >;
    ShippingTimeout: TypedContractEvent<
      ShippingTimeoutEvent.InputTuple,
      ShippingTimeoutEvent.OutputTuple,
      ShippingTimeoutEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
