apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
  namespace: dev
  labels:
    app: payments-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
        - name: payments-service
          image: dgpthinh/payments-service:v1
          command: ["yarn", "run", "dev:payments"]
          ports:
            - containerPort: 3005
          readinessProbe:
            tcpSocket:
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3005
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            limits:
              cpu: "300m"
              memory: "384Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: payments-service
              mountPath: /app
            - name: node-modules
              mountPath: /app/node_modules
      volumes:
        - name: payments-service
          emptyDir: {}
        - name: payments-node-modules
          emptyDir: {}