services:
  identity-service:
    depends_on:
      db-shared:
        condition: service_healthy

  notifications-service:
    depends_on:
      db-shared:
        condition: service_healthy

  artwork-service:
    depends_on:
      db-shared:
        condition: service_healthy

  orders-service:
    depends_on:
      db-shared:
        condition: service_healthy

  messaging-service:
    depends_on:
      db-shared:
        condition: service_healthy

  payments-service:
    depends_on:
      db-shared:
        condition: service_healthy

  events-service:
    depends_on:
      db-shared:
        condition: service_healthy

  community-service:
    depends_on:
      db-shared:
        condition: service_healthy
