{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecrets.name | quote }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "artium-backend.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- with .Values.sealedSecrets.encryptedData }}
    {{- toYaml . | nindent 4 }}
    {{- else }}
    placeholder: AgPLACEHOLDER_REPLACE_WITH_KUBESEAL_OUTPUT
    {{- end }}
  template:
    metadata:
      name: {{ .Values.sealedSecrets.name | quote }}
      namespace: {{ .Values.namespace.name | quote }}
      labels:
        {{- include "artium-backend.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
