apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: artium-backend-secrets
  namespace: artium-prod
spec:
  encryptedData:
    stripe-api-key: AgPLACEHOLDER_STRIPE_API_KEY
    jwt-secret: AgPLACEHOLDER_JWT_SECRET
    platform-private-key: AgPLACEHOLDER_PLATFORM_PRIVATE_KEY
    gcs-key-json: AgPLACEHOLDER_GCS_KEY_JSON
    postgres-password: AgPLACEHOLDER_POSTGRES_PASSWORD
    redis-password: AgPLACEHOLDER_REDIS_PASSWORD
    rabbitmq-password: AgPLACEHOLDER_RABBITMQ_PASSWORD
  template:
    metadata:
      name: artium-backend-secrets
      namespace: artium-prod
    type: Opaque
