apiVersion: v2
name: artium-backend
description: Artium backend production Kubernetes foundation
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    alias: postgresql
    version: 17.1.0
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: redis
    alias: redis
    version: 23.1.1
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: rabbitmq
    alias: rabbitmq
    version: 16.0.16
    repository: oci://registry-1.docker.io/bitnamicharts
